#this is for production build test, this is kind of simpley running helm install sleepr "k8s/sleepr".
#the images are already being built and pushed on docker hub based on github work flow.
apiVersion: skaffold/v4beta11
kind: Config
deploy:
  helm:
    releases:
      - name: sleepr
        chartPath: ./k8s/sleepr
        valuesFiles:
          - ./k8s/sleepr/values-prod.yaml
        setValues:
          global.environment: prod
