#values for dev environement
global:
  environment: dev
auth:
  image: anup84/auth:latest
  command: ['pnpm', 'run', 'start:dev', 'auth']
reservations:
  image: anup84/reservations:latest
  command: ['pnpm', 'run', 'start:dev', 'reservations']
payments:
  image: anup84/payments:latest
  command: ['pnpm', 'run', 'start:dev', 'payments']
notifications:
  image: anup84/notifications:latest
  command: ['pnpm', 'run', 'start:dev', 'notifications']
